name: version1
description: "RV Truck Fleet Management App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.6
  provider: ^6.1.2
  image_picker: ^1.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.2
  uuid: ^4.3.3
  intl: ^0.19.0
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  # Removed file_picker due to compatibility issues
  # file_picker: ^6.2.0
  # Removed potentially problematic packages for build
  # pdf: ^3.10.8
  # printing: ^5.12.0
  # excel: ^4.0.2
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  # Removed due to compatibility issues
  # flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "logo.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - logo.jpg