import 'package:flutter/material.dart';
import '../models/trip_model.dart';
import '../models/broker_model.dart';
import '../models/vehicle_model.dart';
import '../models/driver_model.dart';
import '../services/supabase_service.dart';
import '../constants/app_colors.dart';

class CreateTripScreen extends StatefulWidget {
  const CreateTripScreen({super.key});

  @override
  State<CreateTripScreen> createState() => _CreateTripScreenState();
}

class _CreateTripScreenState extends State<CreateTripScreen> {
  final _formKey = GlobalKey<FormState>();
  final _fromLocationController = TextEditingController();
  final _toLocationController = TextEditingController();
  final _distanceController = TextEditingController();
  final _tonnageController = TextEditingController();
  final _ratePerTonController = TextEditingController();
  final _commissionRateController = TextEditingController(text: '0');
  final _notesController = TextEditingController();

  String? _selectedVehicleId;
  String? _selectedDriverId;
  String? _selectedBrokerId;
  
  List<VehicleModel> _vehicles = [];
  List<DriverModel> _drivers = [];
  List<BrokerModel> _brokers = [];
  
  bool _isLoading = false;
  bool _isSubmitting = false;

  @override
  void initState() {
    super.initState();
    _loadData();
  }

  @override
  void dispose() {
    _fromLocationController.dispose();
    _toLocationController.dispose();
    _distanceController.dispose();
    _tonnageController.dispose();
    _ratePerTonController.dispose();
    _commissionRateController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  Future<void> _loadData() async {
    setState(() => _isLoading = true);
    
    try {
      final vehicles = await SupabaseService.getVehicles();
      final drivers = await SupabaseService.getDrivers();
      final brokers = await SupabaseService.getBrokers();
      
      print('=== CREATE TRIP: Data loaded ===');
      print('Vehicles count: ${vehicles.length}');
      print('Drivers count: ${drivers.length}');
      print('Brokers count: ${brokers.length}');
      
      if (drivers.isNotEmpty) {
        print('First driver: ${drivers.first.name} (${drivers.first.id})');
      }
      
      setState(() {
        _vehicles = vehicles;
        _drivers = drivers;
        _brokers = brokers;
        _isLoading = false;
      });
    } catch (e) {
      setState(() => _isLoading = false);
      print('Error loading data: $e');
      _showErrorSnackBar('Failed to load data: $e');
    }
  }

  void _showErrorSnackBar(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: Colors.red,
      ),
    );
  }

  void _showSuccessSnackBar(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: Colors.green,
      ),
    );
  }

  double _calculateTotalRate() {
    final tonnage = double.tryParse(_tonnageController.text) ?? 0.0;
    final ratePerTon = double.tryParse(_ratePerTonController.text) ?? 0.0;
    return tonnage * ratePerTon;
  }

  double _calculateCommission() {
    final totalRate = _calculateTotalRate();
    final commissionRate = double.tryParse(_commissionRateController.text) ?? 0.0;
    return totalRate * (commissionRate / 100);
  }

  Future<void> _submitTrip() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedVehicleId == null || _selectedDriverId == null) {
      _showErrorSnackBar('Please select vehicle and driver');
      return;
    }

    setState(() => _isSubmitting = true);

    try {
      final trip = TripModel(
        id: '', // Will be generated by database
        lrNumber: '', // Will be auto-generated
        vehicleId: _selectedVehicleId!,
        driverId: _selectedDriverId!,
        brokerId: _selectedBrokerId?.isEmpty == true ? null : _selectedBrokerId,
        fromLocation: _fromLocationController.text.trim(),
        toLocation: _toLocationController.text.trim(),
        distanceKm: double.tryParse(_distanceController.text),
        tonnage: double.tryParse(_tonnageController.text),
        ratePerTon: double.tryParse(_ratePerTonController.text),
        totalRate: _calculateTotalRate(),
        commissionAmount: _calculateCommission(),
        status: 'assigned',
        notes: _notesController.text.trim().isEmpty ? null : _notesController.text.trim(),
        createdAt: DateTime.now(),
      );

      final createdTrip = await SupabaseService.createTrip(trip);
      
      _showSuccessSnackBar('Trip created successfully! LR Number: ${createdTrip.lrNumber}');
      
      // Add a small delay to ensure the snackbar is shown
      await Future.delayed(const Duration(milliseconds: 500));
      
      if (mounted) {
        Navigator.of(context).pop(createdTrip);
      }
    } catch (e) {
      _showErrorSnackBar('Failed to create trip: $e');
    } finally {
      setState(() => _isSubmitting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create New Trip'),
        backgroundColor: AppColors.primaryBlue,
        foregroundColor: Colors.white,
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _buildSectionHeader('Trip Details'),
                    const SizedBox(height: 16),
                    
                    // From Location
                    TextFormField(
                      controller: _fromLocationController,
                      decoration: const InputDecoration(
                        labelText: 'From Location *',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.location_on),
                      ),
                      validator: (value) {
                        if (value == null || value.trim().isEmpty) {
                          return 'Please enter from location';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 16),
                    
                    // To Location
                    TextFormField(
                      controller: _toLocationController,
                      decoration: const InputDecoration(
                        labelText: 'To Location *',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.location_on),
                      ),
                      validator: (value) {
                        if (value == null || value.trim().isEmpty) {
                          return 'Please enter to location';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 16),
                    
                    // Distance
                    TextFormField(
                      controller: _distanceController,
                      decoration: const InputDecoration(
                        labelText: 'Distance (km)',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.straighten),
                        suffixText: 'km',
                      ),
                      keyboardType: TextInputType.number,
                      onChanged: (value) => setState(() {}), // Trigger rebuild for calculations
                    ),
                    const SizedBox(height: 16),
                    
                    // Tonnage
                    TextFormField(
                      controller: _tonnageController,
                      decoration: const InputDecoration(
                        labelText: 'Tonnage *',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.scale),
                        suffixText: 'tons',
                      ),
                      keyboardType: TextInputType.number,
                      validator: (value) {
                        if (value == null || value.trim().isEmpty) {
                          return 'Please enter tonnage';
                        }
                        if (double.tryParse(value) == null || double.parse(value) <= 0) {
                          return 'Please enter valid tonnage';
                        }
                        return null;
                      },
                      onChanged: (value) => setState(() {}), // Trigger rebuild for calculations
                    ),
                    const SizedBox(height: 16),
                    
                    // Rate per Ton
                    TextFormField(
                      controller: _ratePerTonController,
                      decoration: const InputDecoration(
                        labelText: 'Rate per Ton *',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.attach_money),
                        suffixText: '₹',
                      ),
                      keyboardType: TextInputType.number,
                      validator: (value) {
                        if (value == null || value.trim().isEmpty) {
                          return 'Please enter rate per ton';
                        }
                        if (double.tryParse(value) == null || double.parse(value) <= 0) {
                          return 'Please enter valid rate';
                        }
                        return null;
                      },
                      onChanged: (value) => setState(() {}), // Trigger rebuild for calculations
                    ),
                    const SizedBox(height: 24),
                    
                    _buildSectionHeader('Assignment'),
                    const SizedBox(height: 16),
                    
                    // Vehicle Selection
                    DropdownButtonFormField<String>(
                      initialValue: _selectedVehicleId,
                      decoration: const InputDecoration(
                        labelText: 'Select Vehicle *',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.local_shipping),
                      ),
                      items: _vehicles.map((vehicle) {
                        return DropdownMenuItem(
                          value: vehicle.id,
                          child: Text('${vehicle.registrationNumber} (${vehicle.vehicleType})'),
                        );
                      }).toList(),
                      onChanged: (value) {
                        setState(() => _selectedVehicleId = value);
                      },
                      validator: (value) {
                        if (value == null) {
                          return 'Please select a vehicle';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 16),
                    
                    // Driver Selection
                    DropdownButtonFormField<String>(
                      initialValue: _selectedDriverId,
                      decoration: const InputDecoration(
                        labelText: 'Select Driver *',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.person),
                      ),
                      items: _drivers.isEmpty 
                        ? [DropdownMenuItem(value: null, child: Text('No drivers available'))]
                        : _drivers.map((driver) {
                            print('Creating dropdown item for driver: ${driver.name} (${driver.id})');
                            return DropdownMenuItem(
                              value: driver.id,
                              child: Text('${driver.name} (${driver.licenseNumber})'),
                            );
                          }).toList(),
                      onChanged: (value) {
                        print('Driver selected: $value');
                        setState(() => _selectedDriverId = value);
                      },
                      validator: (value) {
                        if (value == null) {
                          return 'Please select a driver';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 16),
                    
                    // Broker Selection
                    DropdownButtonFormField<String?>(
                      value: _selectedBrokerId,
                      decoration: const InputDecoration(
                        labelText: 'Select Broker',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.business),
                      ),
                      items: [
                        const DropdownMenuItem<String?>(
                          value: null,
                          child: Text('No Broker'),
                        ),
                        ..._brokers.map((broker) {
                          return DropdownMenuItem<String?>(
                            value: broker.id,
                            child: Text('${broker.name} (${broker.company})'),
                          );
                        }).toList(),
                      ],
                      onChanged: (value) {
                        setState(() => _selectedBrokerId = value);
                      },
                    ),
                    const SizedBox(height: 16),
                    
                    // Commission Rate
                    TextFormField(
                      controller: _commissionRateController,
                      keyboardType: TextInputType.number,
                      decoration: const InputDecoration(
                        labelText: 'Commission Rate (%)',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.percent),
                        suffixText: '%',
                      ),
                      onChanged: (value) {
                        setState(() {}); // Trigger rebuild to update financial summary
                      },
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Please enter commission rate';
                        }
                        final rate = double.tryParse(value);
                        if (rate == null || rate < 0 || rate > 100) {
                          return 'Commission rate must be between 0 and 100';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 24),
                    
                    _buildSectionHeader('Financial Summary'),
                    const SizedBox(height: 16),
                    
                    // Financial Summary Card
                    Card(
                      child: Padding(
                        padding: const EdgeInsets.all(16.0),
                        child: Column(
                          children: [
                            _buildFinancialRow('Total Rate', '₹${_calculateTotalRate().toStringAsFixed(2)}'),
                            const Divider(),
                            _buildFinancialRow('Commission (${_commissionRateController.text}%)', '₹${_calculateCommission().toStringAsFixed(2)}'),
                            const Divider(),
                            _buildFinancialRow('Net Amount', '₹${(_calculateTotalRate() - _calculateCommission()).toStringAsFixed(2)}', isTotal: true),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(height: 24),
                    
                    _buildSectionHeader('Additional Information'),
                    const SizedBox(height: 16),
                    
                    // Notes
                    TextFormField(
                      controller: _notesController,
                      decoration: const InputDecoration(
                        labelText: 'Notes',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.note),
                      ),
                      maxLines: 3,
                    ),
                    const SizedBox(height: 32),
                    
                    // Submit Button
                    SizedBox(
                      width: double.infinity,
                      height: 50,
                      child: ElevatedButton(
                        onPressed: _isSubmitting ? null : _submitTrip,
                        style: ElevatedButton.styleFrom(
                          backgroundColor: AppColors.primaryBlue,
                          foregroundColor: Colors.white,
                        ),
                        child: _isSubmitting
                            ? const CircularProgressIndicator(color: Colors.white)
                            : const Text(
                                'Create Trip',
                                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                              ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
    );
  }

  Widget _buildSectionHeader(String title) {
    return Text(
      title,
      style: const TextStyle(
        fontSize: 18,
        fontWeight: FontWeight.bold,
        color: AppColors.primaryBlue,
      ),
    );
  }

  Widget _buildFinancialRow(String label, String value, {bool isTotal = false}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8.0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(
            label,
            style: TextStyle(
              fontSize: isTotal ? 16 : 14,
              fontWeight: isTotal ? FontWeight.bold : FontWeight.normal,
            ),
          ),
          Text(
            value,
            style: TextStyle(
              fontSize: isTotal ? 16 : 14,
              fontWeight: isTotal ? FontWeight.bold : FontWeight.normal,
              color: isTotal ? AppColors.primaryBlue : null,
            ),
          ),
        ],
      ),
    );
  }
}

